{ ... }:
{
  imports = [
    ./terminals/alacritty.nix
    ./shells/bash.nix
    ./bat.nix
    ./eza.nix
    ./shells/fish.nix
    ./terminals/ghostty.nix
    ./git.nix
    ./gpg.nix
    ./gtk.nix
    ./helix.nix
    ./terminals/hyper.nix
    ./ideavim.nix
    ./shells/ion.nix
    ./kde.nix
    ./terminals/kitty.nix
    ./neovim.nix
    ./shells/nushell.nix
    ./shells/powershell.nix
    ./terminals/rio.nix
    ./ssh.nix
    ./volta.nix
    ./vscode.nix
    ./terminals/wezterm.nix
    ./zed.nix
    ./zellij.nix
    ./shells/zsh.nix
  ];
}
